# Generate 16x16 mono bitmaps (32 bytes, row-major MSB first) for ST7735 navigation Chinese.
import os
from PIL import Image, ImageDraw, ImageFont

_RAW = "车位已满进入后左手边向南直行米东第一个路口再右无径车牌"
UNIQUE = []
for c in _RAW:
    if c not in UNIQUE:
        UNIQUE.append(c)
UNIQUE = "".join(UNIQUE)
FONT_CANDIDATES = [
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simhei.ttf",
    r"C:\Windows\Fonts\simsun.ttc",
]

def load_font(size=13):
    for p in FONT_CANDIDATES:
        if os.path.isfile(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def glyph_to_bytes(im):
    """im: mode '1', size 16x16"""
    out = bytearray(32)
    for y in range(16):
        row16 = 0
        for x in range(16):
            v = im.getpixel((x, y))
            if v:
                row16 |= 0x8000 >> x
        out[y * 2] = (row16 >> 8) & 0xFF
        out[y * 2 + 1] = row16 & 0xFF
    return bytes(out)


def render_char(ch, font):
    im = Image.new("1", (16, 16), 0)
    dr = ImageDraw.Draw(im)
    bbox = dr.textbbox((0, 0), ch, font=font)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    ox = max(0, (16 - w) // 2 - bbox[0])
    oy = max(0, (16 - h) // 2 - bbox[1])
    dr.text((ox, oy), ch, font=font, fill=1)
    return glyph_to_bytes(im)


def generate_text() -> str:
    font = load_font(13)
    rows = []
    for ch in UNIQUE:
        b = render_char(ch, font)
        rows.append((ch, b))

    out = []
    out.append("/* Auto-generated by gen_nav_hz.py */")
    out.append("static const uint8_t st7735_hz_font[][32] = {")
    for ch, b in rows:
        hx = ",".join(f"0x{x:02X}" for x in b)
        out.append(f"  /* {ch} */ {{{hx}}},")
    out.append("};")
    out.append(f"#define ST7735_HZ_COUNT ({len(UNIQUE)}u)")
    out.append("")
    return "\n".join(out)


def main():
    # IMPORTANT: Do not use shell redirection in PowerShell (it may create UTF-16 output with NULs).
    # We write the file in UTF-8 explicitly to keep Keil happy.
    target = os.path.join(os.path.dirname(__file__), "st7735_hz_font.inc")
    txt = generate_text()
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write(txt)
    print(f"Wrote {target}")


if __name__ == "__main__":
    main()
